# Generated by Django 3.2.5 on 2021-12-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='data',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
